appName: book-rating-app-v1
appNamespace: graphql-system

deployment:
  maxSurge: 40%
  maxUnavailable: 10%
  replicaCount: 1
  pod:
    label: book-rating-app
    generation: "v1"
    version: "istio"
    port: 9080
