appName: book-rating-app-v1
appNamespace: graphql-system

configMap:
  name: book-rating-app-v1-conf
  serverVersion:
    key: SERVICE_VERSION
    value: v-faulty

deployment:
  maxSurge: 40%
  maxUnavailable: 10%
  replicaCount: 1
  pod:
    label: book-rating-app
    generation: "v1"
    version: "1.2.0"
    port: 9080
