apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredPodNamespace
metadata:
  name: must-deploy-in-namespace
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    namespace: dev