host: '*'
appNamespace: istio-stg

vs:
  name: product-app-vs
  route:
    name: product-app-http-route
dr:
  name: product-app-dr
  subset:
    name: product-app-subset

pod:
  label: product-app
  port: 9080

service:
  name: product-app-svc
  domain: svc.cluster.local

gateway:
  name: product-app-gateway
  ingress:
    label: istio-ingressgateway
