targetNamespace: argocd
project:
  name: beauty-proj
  sourceRepos: https://github.com/saifsust/DevOps.git
  destination:
      namespace: graphql-system
      server: https://kubernetes.default.svc
secret:
  name: beauty-proj-secret
  repoURL: https://github.com/saifsust/DevOps.git
  username: saiful.sust.cse@gmail.com
  password: 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

application:
  name: beauty-app
  destination:
     server: https://kubernetes.default.svc
     namespace: graphql-system
  source:
    repoURL: https://github.com/saifsust/DevOps.git
    path: helm/istio/beauty-app
    targetRevision: main
    helm: values-frontend.yaml