input{
  file{
         path => ["/var/log/elasticsearch/elasticsearch.log"]
         start_position => "beginning"
         tags => [ "infra_master_system" ]
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.0.144:9200"]
    index => "logstash-%{+YYYY.MM.dd}"

    user => "logstash_admin"
    password => "bjit1234"

    ssl_enabled => true
    ssl_certificate_authorities => ["/opt/elasticsearch/v94/config/certs/ca.crt"]
  }

  stdout { codec => rubydebug }
}
