apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ratings-to-review
  namespace: {{ .Values.appNamespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.rating }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: {{ .Values.network.review }}