apiVersion: v1
kind: Secret
metadata:
  name: {{- .Values.secret.name }}
  namespace: {{- .Values.appNamespace }}
#  annotations:
#    book.com/book-rating-mysql-app: "mysql-app"
type: Opaque
data:
  {{ .Values.secret.password.key }}: {{ .Values.secret.password.value }}