apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.frontend.destinationRule.name }}
  namespace: {{ .Values.targetNamespace }}
spec:
  host: {{ .Values.frontend.frontendAppSvc }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
  subsets:
    - name: {{ .Values.frontend.destinationRule.subset.name}}
      labels:
        {{ range .Values.frontend.destinationRule.selectors}}
         app: {{ .appLabel }}
         version: {{ .appVersion }}
        {{ end }}
      trafficPolicy:
         loadBalancer:
           simple: ROUND_ROBIN