apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.frontend.virtualService.name }}
  namespace: {{ .Values.targetNamespace }}
spec:
  hosts:
    - {{ .Values.frontend.host | quote }}
  gateways:
    - {{ .Values.frontend.gateway.name }}
  http:
    - name: {{ .Values.frontend.virtualService.http.name }}
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ .Values.frontend.frontendAppSvc }}
            subset: {{ .Values.frontend.destinationRule.subset.name }}