apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.frontend.gateway.name }}
  namespace: {{ .Values.frontend.gateway.namespace }}
spec:
  selector:
    app: istio-ingressgateway
    app.kubernetes.io/name: istio-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.frontend.host }}