FROM mongo:8.0.8
WORKDIR /app/data/
COPY ratings_data.json /app/data/
COPY script.sh /docker-entrypoint-initdb.d/

RUN chown -R mongodb:mongodb /app

RUN chmod +x /docker-entrypoint-initdb.d/script.sh

USER mongodb