apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: details
    name: details
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: details
    template:
      metadata:
        labels:
          app: details
      spec:
        containers:
        - env:
          - name: ENABLE_EXTERNAL_BOOK_SERVICE
            value: "true"
          - name: DO_NOT_ENCRYPT
            value: "false"
          image: saifsust/details:istio
          imagePullPolicy: IfNotPresent
          name: details
          ports:
          - containerPort: 9080
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ratings
      version: v1
    name: ratings-v1
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ratings
        version: v1
    template:
      metadata:
        labels:
          app: ratings
          version: v1
      spec:
        containers:
        - image: saifsust/ratings:istio
          imagePullPolicy: IfNotPresent
          name: ratings-v1
          ports:
          - containerPort: 9080
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ratings
      version: v2
    name: ratings-v2
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ratings
        version: v2
    template:
      metadata:
        labels:
          app: ratings
          version: v2
      spec:
        containers:
        - env:
          - name: SERVICE_VERSION
            value: v2
          - name: DB_TYPE
            value: mysql
          - name: MYSQL_DB_HOST
            value: mysql-svc.cassandra.svc.cluster.local
          - name: MYSQL_DB_PORT
            value: "3306"
          - name: MYSQL_DB_USER
            value: root
          - name: MYSQL_DB_PASSWORD
            value: password
          image: saifsust/ratings:istio
          imagePullPolicy: IfNotPresent
          name: ratings-v2
          ports:
          - containerPort: 9080
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ratings
      version: v3
    name: ratings-v3
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ratings
        version: v3
    template:
      metadata:
        labels:
          app: ratings
          version: v3
      spec:
        containers:
        - env:
          - name: SERVICE_VERSION
            value: v2
          - name: MONGO_DB_URL
            value: mongodb://mongodb-svc.cassandra.svc.cluster.local:27017/test
          image: saifsust/ratings:istio
          imagePullPolicy: IfNotPresent
          name: ratings-v3
          ports:
          - containerPort: 9080
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: reviews
      version: v1
    name: reviews-v1
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: reviews
        version: v1
    template:
      metadata:
        labels:
          app: reviews
          version: v1
      spec:
        containers:
        - env:
          - name: ENABLE_RATINGS
            value: "false"
          image: saifsust/reviews:istio
          imagePullPolicy: IfNotPresent
          name: reviews
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: reviews
      version: v2
    name: reviews-v2
    namespace: cks
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: reviews
        version: v2
    template:
      metadata:
        labels:
          app: reviews
          version: v2
      spec:
        containers:
        - env:
          - name: ENABLE_RATINGS
            value: "true"
          - name: STAR_COLOR
            value: red
          - name: RATINGS_HOSTNAME
            value: ratings-svc
          - name: SERVICES_DOMAIN
            value: cks.svc.cluster.local
          - name: RATINGS_SERVICE_PORT
            value: "9080"
          image: saifsust/reviews:istio
          imagePullPolicy: IfNotPresent
          name: reviews
          ports:
          - containerPort: 9080
            protocol: TCP
  ## Deployments Service
- apiVersion: v1
  kind: Service
  metadata:
    name: details-svc
    namespace: cks
  spec:
    ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: details
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: ratings-svc
    namespace: cks
  spec:
    ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: ratings
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: reviews-svc
    namespace: cks
  spec:
    ports:
    - nodePort: 30001
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: reviews
    type: NodePort
  ## Cilium Network Policies
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-dns
    namespace: cks
  spec:
    egress:
    - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
          - matchPattern: '*'
    endpointSelector: {}
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-ratings-v2-to-mysql-server
    namespace: cks
  spec:
    egress:
    - toEndpoints:
      - matchLabels:
          app: mysql-server
          io.kubernetes.pod.namespace: cassandra
      toPorts:
      - ports:
        - port: "3306"
          protocol: TCP
    endpointSelector:
      matchLabels:
        app: ratings
        version: v2
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-ratings-v3-to-mongodb
    namespace: cks
  spec:
    egress:
    - toEndpoints:
      - matchLabels:
          app: mongodb
          io.kubernetes.pod.namespace: cassandra
      toPorts:
      - ports:
        - port: "27017"
          protocol: TCP
    endpointSelector:
      matchLabels:
        app: ratings
        version: v3
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-ratings-inbound-from-reviews
    namespace: cks
  spec:
    endpointSelector:
      matchLabels:
        app: ratings
    ingress:
    - fromEndpoints:
      - matchLabels:
          app: reviews
          version: v2
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-reviews-inbound-from-world
    namespace: cks
  spec:
    endpointSelector:
      matchLabels:
        app: reviews
    ingress:
    - fromEntities:
      - world
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-reviews-v2-to-ratings
    namespace: cks
  spec:
    egress:
    - toEndpoints:
      - matchLabels:
          app: ratings
      toPorts:
      - ports:
        - port: "9080"
          protocol: TCP
    endpointSelector:
      matchLabels:
        app: reviews
        version: v2
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: deny-all
    namespace: cks
  spec:
    egress:
    - {}
    endpointSelector: {}
    ingress:
    - {}
kind: List
metadata:
  resourceVersion: ""
