apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mongodb
    name: mongodb
    namespace: cassandra
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mongodb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongodb
      spec:
        containers:
        - image: saifsust/mongodb-server:istio
          imagePullPolicy: Always
          name: mongodb-server
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mysql-server
    name: mysql-server
    namespace: cassandra
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mysql-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mysql-server
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          image: saifsust/mysql-server:istio
          imagePullPolicy: Always
          name: mysql-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mongodb
    name: mongodb-svc
    namespace: cassandra
  spec:
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mysql-server
    name: mysql-svc
    namespace: cassandra
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: allow-mongodb-from-ratings-v3
    namespace: cassandra
  spec:
    endpointSelector:
      matchLabels:
        app: mongodb
    ingress:
    - fromEndpoints:
      - matchLabels:
          app: ratings-v3
          io.kubernetes.pod.namespace: cks
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: deny-all
    namespace: cassandra
  spec:
    egress:
    - {}
    endpointSelector: {}
    ingress:
    - {}
kind: List
metadata:
  resourceVersion: ""
