apiVersion: v2
name: book detail app
version: 0.0.1
kubeVersion: 1.33.4
description:  A book information details are provided by details app
keywords:
  - productId
  - External book details
home: https://github.com/saifsust/DevOps/tree/main/istio
sources:
  - https://github.com/saifsust/DevOps.git
maintainers:
  - name: SAIFUL ISLAM
    email: saiful.sust.cse@gmail.com
    url: https://www.linkedin.com/in/saiful-islam-340b51133
appVersion: 0.0.1
annotations:
  maintainer: saiful.sust.cse@gmail.com