appName: book-details
appNamespace: istio-pod

configMap:
  name: book-details-app-conf
  isForExternalCallKey: isForExternalCall
  isForExternalCallVal: false

deployment:
  replicaCount: 2
  maxSurge: 40%
  maxUnavailable: 10%
  pod:
    label: book-details-app
    version: "-version-"
    tag: istio
    port: 9080

service:
  name: book-details-app-svc
  type: ClusterIP

