apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredNamespace
metadata:
 name: required-namespace
spec:
 match:
  kinds:
  - apiGroups: [""]
    kinds: ["Pod", "Secret", "ConfigMap"]
  - apiGroups: ["apps/v1"]
    kinds: ["Deployment", "StatefulSet"]
 parameters:
   namespace: graphql-system