appName: book-rating-app-v3
appNamespace: graphql-system

configMap:
  name: book-rating-app-v3-conf
  serverVersion:
    key: SERVICE_VERSION
    value: v2
  url:
    key: MONGO_DB_URL
    mongodbHost: mongodb://mongodb-app-svc
    domainDb: svc.cluster.local:27017/test

deployment:
  maxSurge: 40%
  maxUnavailable: 10%
  replicaCount: 0
  pod:
    label: book-rating-app
    generation: v3
    version: "1.0.0"
    port: 9080
