apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DeploymentConfiguration
metadata:
  name: deployment-conf
spec:
  match:
   kinds:
   - apiGroups: ["apps"]
     kinds: ["Deployment", "DaemonSet"]
  parameters:
    namespaces: ["dev", "stg"]
    labels:
    - key: app-env
      value: test
    podLabel: tier
    replicas:
        minReplicas: 2
        maxReplicas: 5
