apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  annotations:
    uddom.io/elastic-search: prod
spec:
  storageClassName: es-storage
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
   path: /usr/local/share/es-storage