apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mysql-server-to-ratings
  namespace: graphql-system
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.mysqlServer }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: {{ .Values.network.rating }}