apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: review-to-product
  namespace: {{ .Values.appNamespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.review }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: {{ .Values.network.product }}