version: "3.8"

services:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data

volumes:
  redis_insight_data: {}
