appNamespace: redis-system

server:
  appName: redis-server
  replicaCount: 1
  image: redis
  imageTag: 8.6.5-alpine

  service:
    type: ClusterIP

insight:
  appName: redis-insight
  replicaCount: 1
  image: redis/redisinsight
  imageTag: latest

  service:
    type: NodePort
    nodePort: 30087