apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.vs.name }}
  namespace: {{ .Values.appNamespace }}
spec:
  gateways:
    - {{ .Values.gateway.name }}
  hosts:
    - {{ .Values.host | quote }}
  http:
    - name: webhook-route
      match:
        - uri:
            prefix: "/validate"
        - uri:
            prefix: "/health"
      route:
        - destination:
            host: {{ printf "%s.%s.%s" .Values.service.name .Values.appNamespace .Values.service.domain }}
            port:
              number: {{ .Values.service.port }}