/**
* docker pull command for download image from docker hub
**/

docker pull mysql
/**
* run images as a container
**/

docker run -dp external-port:port-internal -e environment-variable (MYSQL_ROOT_PASSWORD) --name=container-name image-name/image-id

/**
* stop all container
*/
docker stop $(docker ps -a -q)

/**
* remove all container
*/
docker rm $(docker ps -a -q)
