apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod-pod
  name: alpine-pod-pod
spec:
  volumes:
    - name: config-volume
      configMap:
        name: log-configmap
  containers:
    - image: alpine:latest
      name: alpine-container
      resources: {}
      command: ["/bin/sh", "-c"]
      args: ["tail -f /config/log.txt"]
      volumeMounts:
        - name: config-volume
          mountPath: /config
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}