appName: webhook-controller
appNamespace: webhook-system

service:
  name: webhook-controller-svc
  type: ClusterIP
#  nodePort: 31002
  ssl:
    port: 443
 #   nodePort: 31443

deployment:
  replicaCount: 1
  maxUnavailable: 10%
  maxSurge: 50%
  pod:
    label: webhook-controller-app
    port: 8081
    targetPort: 8081
    version: 6.0.99