appName: webhook-server
appNamespace: graphql-system

service:
  name: webhook-server-svc
  type: ClusterIP
#  nodePort: 31002
  ssl:
    port: 443
 #   nodePort: 31443

deployment:
  replicaCount: 1
  maxUnavailable: 10%
  maxSurge: 50%
  pod:
    label: webhook-server-app
    port: 8081
    targetPort: 8081
    version: 2.0.99