kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.existingClaim }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: es-storage
  volumeName: es-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  selector:
    matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values:
      - broker-server