appName: book-mongodb-app
appNamespace: istio-stg

service:
  name: rating-mongodb-app-svc
  type: ClusterIP
  # nodePort: 31108

deployment:
  replicaCount: 1
  maxSurge: 40%
  maxUnavailable: 10%
  pod:
    label: rating-mongodb-app
    version: "1.0.99"
    port: 27017

