namespaceOverride: "argo-system"
commonLabels:
  uddom.io/proj: argo-workflow

controller:
  name: workflow-controller
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-master
server:
  # -- Deploy the Argo Server
  enabled: true
  name: server
  serviceType: NodePort
  serviceNodePort:  32746
  # -- [Tolerations] for use with node taints
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule

  # -- Assign custom [affinity] rules
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-master
  extraArgs:
  - --auth-mode=server
useStaticCredentials: true