nameOverride: argocd
namespaceOverride: "argo-system"

global:
  additionalLabels:
    uddom.io/proj: argocd
    uddom.io/env: prod
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      # -- Default node affinity rules. Either: `none`, `soft` or `hard`
      type: hard
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k8s-master

## Application controller
controller:
  name: application-controller

## Server
server:
  name: server

## Repo Server
repoServer:
  name: repo-server

applicationSet:
  name: applicationset-controller

dex:
  # -- Enable dex
  enabled: true
  # -- Dex name
  name: dex-server

notifications:
  enabled: true

commitServer:
  enabled: false