apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-server
  name: mysql-svc
  namespace: secure-app
spec:
  ports:
  - nodePort: 31664
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-server
  type: NodePort
status:
  loadBalancer: {}
