apiVersion: v1
kind: Service
metadata:
  labels:
    app: productpage
  name: productpage-svc
  namespace: secure-app
spec:
  ports:
  - nodePort: 30099
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
  type: NodePort
status:
  loadBalancer: {}
