apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-v2
  name: ratings-v2-svc
  namespace: secure-app
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: ratings-v2
  type: ClusterIP
status:
  loadBalancer: {}
