apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-v3
  name: ratings-v3-svc
  namespace: secure-app
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: ratings-v3
  type: ClusterIP
status:
  loadBalancer: {}
