apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviews-v1
  name: reviews-v1-svc
  namespace: secure-app
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: reviews-v1
  type: ClusterIP
status:
  loadBalancer: {}
