apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-controller
  name: jenkins-controller
  namespace: jenkins-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-controller
  template:
    metadata:
      labels:
        app: jenkins-controller
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: "Equal"
        effect: NoSchedule
      affinity:
        nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/hostname 
               operator: In
               values:
               - controlplane
      volumes:
      - name: jenkins-home-directory
        persistentVolumeClaim:
         claimName: jenkins-pvc 
      - name: certs
        projected:
         sources:
         - secret:
            name: kube-conf-secret
            items:
            - key: tls.crt
              path: client.crt
            - key: tls.key
              path: client.key
         - configMap:
            name: jenkins-kube-conf
            items:
            - key: config
              path: config
         - configMap:
             name: kube-root-ca.crt
             items:
               - key: ca.crt
                 path: ca.crt
         - secret:
             name: jenkins-cert
             items:
             - key: cert
               path: cert.pem
             - key: key
               path: key.pem
             - key: ca
               path: ca.pem
      containers:
      - image: saifsust/jenkins:docker
        name: jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home-directory
          mountPath: /var/jenkins_home
        - name: certs
          mountPath: /home/.docker
        env:
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_HOST
          valueFrom:
           configMapKeyRef:
              name: jenkins-conf
              key: host
