apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-controller
  name: jenkins-svc
  namespace: jenkins-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
    name: ui-tcp
  - port: 50000
    targetPort: 50000
    protocol: TCP
    nodePort: 30085
    name: agent-protocol
  selector:
    app: jenkins-controller
  type: NodePort
status:
  loadBalancer: {}
