apiVersion: v1
kind: PersistentVolume
metadata:
 name: jenkins-pv
spec:
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname 
         operator: In
         values:
         - controlplane
 storageClassName: local-storage
 accessModes:
 - ReadWriteMany
 capacity:
  storage:  500Mi
 hostPath:
    path: /opt/jenkins
