apiVersion: v2
name: nginx reverse proxy configuration
version: 0.0.1
description:  This proxy will be used to bypass all apps actual host.
maintainers:
  - name: SAIFUL ISLAM
    email: saiful.sust.cse@gmail.com
    url: https://www.linkedin.com/in/saiful-islam-340b51133
appVersion: 0.0.1
annotations:
  maintainer: saiful.sust.cse@gmail.com