apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny
  namespace: secure-app
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - toPorts:
      - ports:
        - port: "53" # DNS resolution. kube-dns allowed to serve k8s service
          protocol: ANY
