pipeline {
    agent any
    stages {
        stage('Docker version checker') {
            steps {
                sh 'docker --version'
            }
        }
        stage('Docker List of Images') {
             steps {
                sh 'docker images'
             }
        }
    }
}
