pipeline {
    agent any
    environment {
        KUBECONFIG = credentials('kube-config')
    }
    stages {
        stage('Docker version checker') {
            steps {
                sh 'docker --version'
            }
        }
        stage('Docker List of Images') {
             steps {
                sh 'docker images'
             }
        }
        stage('Kubernetes List of Pods'){
            steps{
                sh 'kubectl get pods'
            }
        }
    }
}
