# Elastic search proxy route
server{
    listen 80;
    server_name kibana.uddom.com;

    location / {
       proxy_pass http://192.168.0.144:5601;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}