# Argo Workflow reverse proxy
server{
    listen 80;
    server_name argoworkflow.uddom.com;

    location / {
       proxy_pass https://192.168.0.140:30080;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
# Argo CD reverse proxy
server{
    listen 80;
    server_name argocd.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30081;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Elastic search proxy route
server{
    listen 80;
    server_name prometheus.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30082;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name grafana.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30083;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name alertmanager.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30084;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name vault.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30085;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name redis.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30087;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name hubble.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30086;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server{
    listen 80;
    server_name kibana.uddom.com;

    location / {
       proxy_pass http://192.168.0.140:30088;

       proxy_http_version 1.1;

       proxy_ssl_verify off;

       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}