apiVersion: v1
data:
  email: {{ .Values.dockerRegistrySecret.email }}
  username: {{ .Values.dockerRegistrySecret.username }}
  password: {{ .Values.dockerRegistrySecret.password }}
  host: {{ printf "tcp://%s:%s" .Values.host .Values.dockerRegistrySecret.port | b64enc}}
kind: Secret
metadata:
  name: {{ .Values.dockerRegistrySecret.name }}
  namespace: {{ .Values.appNamespace }}
