apiVersion: v1
kind: PersistentVolume
metadata:
 name: {{ .Values.jenkinsHomeVolume.pvName }}
spec:
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname 
         operator: In
         values:
         - {{ .Values.nodeName }}
 storageClassName: {{ .Values.jenkinsHomeVolume.storageClassName }}
 accessModes:
 - {{ .Values.jenkinsHomeVolume.accessMode }}
 capacity:
  storage:  {{ .Values.jenkinsHomeVolume.capacity }}
 hostPath:
    path: {{ .Values.jenkinsHomeVolume.hostPath }}
