apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.appNamespace }}
data:
  index.html: |
    <h1> Hello Frontend User. Request Receives within <strong> Frontend </strong> </h1>