apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: {{ .Values.replicaCounts }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: {{ .Values.pod.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.label }}
    spec:
      volumes:
        - name: html
          configMap:
            name: {{ .Values.configMap.name }}
      containers:
        - name: app
          image: nginx:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - while true; do curl http://{{printf "%s.%s.svc.cluster.local:80" .Values.backend.serviceName .Values.backend.appNamespace }} && sleep 5; done
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
              protocol: TCP