apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.appNamespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.pod.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.pod.port }}
      targetPort: {{ .Values.deployment.pod.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      name: http