#/etc/systemd/system/docker.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2376 \
--tlsverify \
--tlscacert=/home/vagrant/.docker/ca.crt \
--tlscert=/home/vagrant/.docker/docker-server.crt \
--tlskey=/home/vagrant/.docker/docker-server.key \
--group=vagrant
