# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

def getNetworkBridge()
  return %x{ip route show | grep default | grep -E "192.168." | awk '{print $5}'}.chomp
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.boot_timeout = 900
  config.vm.box_check_update = false
  
  config.vm.define "docker-master" do |master|
    master.vm.provider "virtualbox" do |masterVm|
      masterVm.name = "docker-master"
      masterVm.memory = 4096
      masterVm.cpus = 2
    end
    master.vm.hostname = "docker-master"
    master.vm.network :public_network, ip: "192.168.0.32", bridge: getNetworkBridge()
  end
end
