apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /home/.docker/ca.crt
        server: https://192.168.96.30:6443
      name: jenkins-cluster
    contexts:
    - context:
        cluster: jenkins-cluster
        user: jenkins-user
      name: jenkins-user@jenkins-cluster
    current-context: jenkins-user@jenkins-cluster
    kind: Config
    preferences: {}
    users:
    - name: jenkins-user
      user:
        client-certificate: /home/.docker/client.crt
        client-key: /home/.docker/client.key
kind: ConfigMap
metadata:
  name: jenkins-kube-conf
  namespace: jenkins-system
