appName: book-rating-app-v2
appNamespace: uddom-beta-stg

configMap:
  name: book-rating-app-v2-conf
  serverVersion:
    key: SERVICE_VERSION
    value: v2
  dbType:
    key: DB_TYPE
    value: mysql
  port:
    key: MYSQL_DB_PORT
    value: 3306
  url:
    key: MYSQL_DB_HOST
    hostService: book-mysql-svc
    domain: svc.cluster.local

secret:
  name: book-rating-app-v2-secret
  username:
    key: MYSQL_DB_USER
    value: cm9vdA==
  password:
    key: MYSQL_DB_PASSWORD
    value: cGFzc3dvcmQ=

deployment:
  maxSurge: 40%
  maxUnavailable: 10%
  replicaCount: 1
  pod:
    label: book-rating-app
    generation: v2
    version: "1.2.0"
    port: 9080
