apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-svc
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.appName}}
    build: {{ .Values.build }}
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.port.containerPort}}
      targetPort: {{.Values.service.targetPort}}
      name: http
      {{ if .Values.service.nodePort}}
      nodePort: {{.Values.service.nodePort}}
      {{end}}