apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-server
  namespace: argocd
spec:
  project: graphql-proj
  sources:
  - helm:
      valueFiles:
        - values-stg.yaml
    path: helm/mock-server
    repoURL: https://github.com/saifsust/DevOps.git
    targetRevision: main
  destination:
    name: graphql-system
    server: https://kubernetes.default.svc