apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: graphql-proj
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: graphql-system
      server: '*'
  sourceRepos:
    - '*'