apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: product-to-review
  namespace: {{ .Values.appNamespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.product }}
  egress:
    - toEndpoints:
        - matchLabels:
            app: {{ .Values.network.review }}
      toPorts:
        - ports:
            - port: "9080"
              protocol: TCP