apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: product-app-world
  namespace: {{ .Values.appNamespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.product }}
  ingress:
    - fromEntities:
        - all