apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rating-to-mysql-server
  namespace: {{ .Values.appNamespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.network.rating }}
  egress:
    - toEndpoints:
        - matchLabels:
            app: {{ .Values.network.mysqlServer }}
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP