apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.configuration.name }}
  namespace: {{ .Values.targetNamespace }}
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: {{ .Values.configuration.source.repoURL }}
    targetRevision: {{ .Values.configuration.source.targetRevision }}
    path: {{ .Values.configuration.source.path }}
    helm:
      valueFiles:
        - {{ .Values.configuration.source.helm }}
  destinations:
    {{ range .Values.configuration.destinations }}
    - server: { { .server } }
      namespace: { { .namespace } }
    {{ end }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=tue
      - Replace=true
