apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name}}
  namespace: {{ .Values.targetNamespace }}
spec:
  sourceRepos:
    - {{ .Values.project.sourceRepos}}
  destinations:
    {{ range .Values.project.destinations }}
    - server: {{ .server }}
      namespace: {{ .namespace }}
    {{ end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'