apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.targetNamespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: {{ .Values.project.name}}
  name: {{ .Values.secret.name }}
  url: {{ .Values.secret.repoURL}}
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}