apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.targetNamespace }}
stringData:
  type: git
  url: {{ .Values.secret.url}}
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}