apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.appNamespace }}
data:
  {{ .Values.secret.username.key }} : {{ .Values.secret.username.value }}
  {{ .Values.secret.password.key }} : {{ .Values.secret.password.value }}