appNamespace: webhook-system
host: '*'

service:
  name: webhook-controller-svc
  domain: svc.cluster.local
  port: 443
  targetPort: 8081

deployment:
  pod:
    label: webhook-controller-app

dr:
  name: webhook-controller-dr
  subset: webhook-controller-subset

vs:
  name: webhook-controller-vs

gateway:
  name: webhook-controller-api-gateway