apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: details
  name: details
  namespace: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: details
    spec:
      containers:
      - image: saifsust/details:istio
        name: details
        ports:
        - containerPort: 9080
        resources: {}
        imagePullPolicy: Always
        env:
        - name: ENABLE_EXTERNAL_BOOK_SERVICE
          value: "true"
        - name: DO_NOT_ENCRYPT
          value: "false"
status: {}
