apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: details
  name: details-svc
  namespace: secure-app
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: details
status:
  loadBalancer: {}