apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ratings
    version: v1
  name: ratings-v1
  namespace: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.3
        name: examples-bookinfo-ratings-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        resources: {}
status: {}