appName: frontend-app
appNamespace: applications
replicaCounts: 1

pod:
  label: frontend-cilium-app

configMap:
  name: frontend-cilium-configmap

service:
  name: frontend-cilium-svc
  type: NodePort
  httpNodePort: 30080
  httpsNodePort: 30443

backend:
  appNamespace: applications
  serviceName: backend-cilium-svc