apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.appNamespace }}
data:
  {{ .Values.configMap.isForExternalCallKey }}: {{ .Values.configMap.isForExternalCallVal | quote }}