apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.maxSurge }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
  selector:
     matchLabels:
        app: {{.Values.deployment.pod.label }}
        version: {{ .Values.deployment.pod.version | quote }}
  template:
    metadata:
      labels:
         app: {{ .Values.deployment.pod.label }}
         version: {{ .Values.deployment.pod.version | quote }}
    spec:
      containers:
        - image: saifsust/details:{{- .Values.deployment.pod.tag }}
          name: app
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.pod.port }}
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: ENABLE_EXTERNAL_BOOK_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: {{ .Values.configMap.isForExternalCallKey | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.deployment.pod.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.deployment.pod.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.deployment.pod.port }}
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 5