apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodAccessControl
metadata:
  name: pod-access-control-constraints
spec:
 match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
 parameters:
  labels:
    app: frontend
    env: dev