apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: mysql-server
  name: mysql-server
  namespace: graphql-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-server
    spec:
      containers:
      - image: saifsust/mysql-server:istio
        name: mysql-server
        resources: {}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
status: {}
