apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.appNamespace }}
data:
  {{ .Values.configMap.enableRating.key }} : {{ .Values.configMap.enableRating.value }}
  {{ .Values.configMap.starColor.key }} : {{ .Values.configMap.starColor.value }}
  {{ .Values.configMap.ratingHostName.key }} : {{ .Values.configMap.ratingHostName.value }}
  {{ .Values.configMap.serviceDomain.key }} : {{ .Values.configMap.serviceDomain.value }}
  {{ .Values.configMap.ratingServicePort.key }} : {{ .Values.configMap.ratingServicePort.value }}