fullnameOverride: elastic-search
namespace: elasticsearch-system
replicas: 1
revisionHistoryLimit: 0

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.2.3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 30200

persistence:
  existingClaim: es-pv
  path: /usr/share/elasticsearch/data
  size: 2Gi

extraEnv:
  "discovery.type": single-node

securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

heapSize: 512m

javaOpts: ""
