fullnameOverride: elastic-search

revisionHistoryLimit: 0

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.2.3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 30200

persistence:
  enabled: true
  existingClaim: "es-pv"
  path: /usr/share/elasticsearch/data
  subPath: ""
  accessMode: ReadWriteMany
  size: 2Gi

extraEnv:
  "discovery.type": single-node

securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

heapSize: 512m

javaOpts: ""
