apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.appNamespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.pod.label }}
    version: {{ .Values.deployment.pod.version | quote }}
  ports:
    - port: {{ .Values.deployment.pod.port }}
      targetPort: {{ .Values.deployment.port }}
      name: http
      protocol: TCP
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}