apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: podmustbeinnamespaces
spec:
 crd:
  spec: 
     names: 
      kind: PodMustBeInNamespaces
      shortNames:
      - pmbin
     validation:
       openAPIV3Schema:
          type: object
          properties:
            namespaces:
               type: array
               items:
                 type: string
 targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package podmustbeinnamespaces
      
      violation[{"msg": msg}]{
         provided := input.review.object.metadata.namespace
         required := input.parameters.namespaces

         not match_any(required, provided)
         msg := sprintf("You must create pods within namespaces %v", [required])
      }
     
      match_any(required, provided){
          some idx;
          required[idx] == provided
      }
