apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.insight.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: {{ .Values.insight.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 25%
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Values.insight.appName .Values.insight.imageTag }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Values.insight.appName .Values.insight.imageTag }}
    spec:
      volumes:
        - name: data
          hostPath:
            path: /tmp
      containers:
        - name: app
          image: {{ printf "%s:%s" .Values.insight.image .Values.insight.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5540
              protocol: TCP
              name: tcp
          volumeMounts:
            - name: data
              mountPath: /usr/share/redis/data