apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.server.appName }}
  namespace: {{ .Values.appNamespace }}
spec:
  serviceName: {{ .Values.server.appName }}
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-%s" .Values.server.appName .Values.server.imageTag }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Values.server.appName .Values.server.imageTag }}
    spec:
      containers:
        - name: app
          image: {{ printf "%s:%s" .Values.server.image .Values.server.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
              name: tcp
          volumeMounts:
            - name: redis-data
              mountPath: /data
volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: {{ .Values.server.persistentVolume.accessModes }}
          resources:
            requests:
              storage: {{ .Values.server.persistentVolume.storage }}