apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.appNamespace }}
data:
  {{ .Values.configMap.serverVersion.key }} : {{ .Values.configMap.serverVersion.value }}