argoNamespace: argocd
appNamespace: graphql-system

k8sServer: https://kubernetes.default.svc

project:
  name: e-book-service-project

secret:
  name: ecommerce-book-service-secret
  url: https://github.com/saifsust/DevOps.git
  username: saiful.sust.cse@gmail.com
  password: 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

network:
  name: cilium-network-policies

applications:
  product:
    name: product-page-app
  configuration:
    name: istio-configuration-app
  details:
    name: book-details
  ratings:
    common:
      name: e-book-ratings-app-common
    v1:
      name: e-book-ratings-app-v1
    v2:
     name: e-book-ratings-app-v2
    v3:
      name: e-book-ratings-app-v3
  review:
    common:
      name: review-app-common
    v1:
      name: review-app-v1
    v2:
      name: review-app-v2
    v3:
      name: review-app-v3
  mysqlServer:
    name: mysql-server-app
  mongodbServer:
    name: mongodb-server-app