[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
CN = webhook-server-svc.graphql-system.svc

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = webhook-server-svc
DNS.2 = webhook-server-svc.graphql-system
DNS.3 = webhook-server-svc.graphql-system.svc
DNS.4 = webhook-server-svc.graphql-system.svc.cluster.local
IP.1  = 192.168.0.30
