targetName: graphql-system
frontend:
  host: beauty-frontend-svc.graphql-system.svc.cluster.local
  dnsIP: 192.168.0.30
  gateway:
    name: beauty-frontend-app-gateway
    namespace: graphql-system
  destinationRule:
    name: beauty-frontend-app-dr
    subset:
      name: beauty-frontend-app-subset
    selectors:
      - app: frontend-app
        version: "v1"
  virtualService:
    name: beauty-frontend-app-vs
    http:
      name: beauty-frontend-app-vs-http
