apiVersion: v1
kind: Service
metadata:
  labels:
    app: tester
  name: tester-svc
  namespace: cks
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tester
  type: ClusterIP